### ISSUE TITLE
Bad description in the korean menu

### ISSUE THREAD

**Issue by Acontreras2k** [manulopez14/Proyecto-Pagina-Web#11]
The description is not professional
What does "apanado" mean??????????
😊

**Comment by Diegocs02** [comment]
do you want to fight or what??? XD

**Comment by luciluci8** [comment]
According to the Spanish dictionary "apanado" is breaded. Keep calm and drink Bangarae banana milk

**Comment by manulopez14** [comment]
> According to the Spanish dictionary "apanado" is breaded. Keep calm and drink Bangarae banana milk

Thank you for this piece of information, i will close this issue since we already know what it means.
